# Site settings
title: Mount Sinai Health System Faculty of Color Network
email: ashley.fowler@mssm.edu
description: > # this means to ignore newlines until "baseurl:"
   the website for MSSM FCON.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diversifyyourscience.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 
array: []

# Build settings
markdown: kramdown

collections:
  instructors:
    output: true
  workshops:
    output: true
  news:
    output: true
